spring.application.name=clients-service
server.port=${SERVER_PORT:8081}
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/clients_db}
spring.datasource.username=${DB_USERNAME:catalogos}
spring.datasource.password=${DB_PASSWORD:catalogos_dev}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
