spring.application.name=logs-service
server.port=${SERVER_PORT:8083}
spring.data.Postgres.uri=${DB_URL:jdbc:postgresql://localhost:5432/logs_db}
spring.datasource.url=${spring.data.Postgres.uri}
spring.datasource.username=${DB_USERNAME:catalogos}
spring.datasource.password=${DB_PASSWORD:catalogos_dev}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
